### ISSUE TITLE
What the actual f*ck?

### ISSUE THREAD

**Issue by LightYagami200** [exercism/job-application-process#1]
Found link to this sh*t on Reddit (https://reddit.com/r/webdev/comments/ucmq1v/the_current_state_of_web_dev/) AND HOLY SHIT THIS IS SOME FUCKED UP LEVEL OF INSANITY.

You guys really want "applicants" to spend days working on this crap for a chance to get interviewed?

**Comment by iHiD** [comment]
I'm closing this as it's not currently adding any value to the conversation. If you'd like to make tangible suggestions as to how hiring can be done well, please take a read of the [README](https://github.com/exercism/job-application-process/blob/main/README.md) and open a new issue. Thank you.
