### ISSUE TITLE
just doing your website for free arent they?

### ISSUE THREAD

**Issue by elYanuki** [exercism/job-application-process#21]
doing this for the chance of beeing considered is a massive scam.. especially since you not only want them to design it but also add the js like what the hell. Every applicant can surely show you some of their projects there is no need for this.. and if you think there is, for some reason, dont make it soo huge.. small 1 or 2 hour job and you can gather the same knowladge
also..might i add, your current website is not responsive at all btw.. its fucked on phones

**Comment by iHiD** [comment]
I'm closing this as it's not currently adding any value to the conversation. If you'd like to make tangible suggestions as to how hiring can be done well, please take a read of the [README](https://github.com/exercism/job-application-process/blob/main/README.md) and open a new issue. Thank you.
