### ISSUE TITLE
Sorry, when did Github become cheap Fiverr?

### ISSUE THREAD

**Issue by OdinsHat** [exercism/job-application-process#23]
17yrs dev experience under my belt in PHP, Python, JS frameworks, server admin, devops and TPO - this, right here, is bull!

**I've been in the industry long enough to know a con when see it!**

It's why you won't get a decent, happy employee. If that's what you even want.

Right now, it reads more like a Fiverr job request that you're getting for free - no one should be conned by this.

You guy's should be ashamed of yourselves asking for as the first step of an interview.

Your own site doesn't even meet the requirements you've set on responsiveness.

Whoever you give this job too should become your new lead dev and replace the plonker who built your site/runs your service.

**Comment by iHiD** [comment]
I'm closing this as it's not currently adding any value to the conversation. If you'd like to make tangible suggestions as to how hiring can be done well, please take a read of the [README](https://github.com/exercism/job-application-process/blob/main/README.md) and open a new issue. Thank you.
