### ISSUE TITLE
Flop

### ISSUE THREAD

**Issue by shobu13** [exercism/job-application-process#25]
![diagnosis-issue-flop.gif](https://user-images.githubusercontent.com/21972673/165473626-83bbec07-a157-47cd-a081-6c963e650f23.gif)

**Comment by iHiD** [comment]
I'm closing this as it's not currently adding any value to the conversation. If you'd like to make tangible suggestions as to how hiring can be done well, please take a read of the [README](https://github.com/exercism/job-application-process/blob/main/README.md) and open a new issue. Thank you.
