### ISSUE TITLE
Pay rate for work not listed

### ISSUE THREAD

**Issue by Bitz** [exercism/job-application-process#4]
An understandable oversight, but the pay rate for this project is not listed anywhere in the readme.

Can you please provide more information about the compensation for what is a *minimum of 6 hours of work*?

Unless... the intent of [Jeremy Walker](https://ihid.info/) is to extract free labour out of desperate developers? 

No, that could not possibly be it, could it? No way Exercism could be simultaneously be [begging for handouts](https://exercism.org/donate) while making would-be applicants jump through time consuming hoops for a CHANCE at an interview?

**Comment by iHiD** [comment]
I'm closing this as it's not currently adding any value to the conversation. If you'd like to make tangible suggestions as to how hiring can be done well, please take a read of the [README](https://github.com/exercism/job-application-process/blob/main/README.md) and open a new issue. Thank you.
