### ISSUE TITLE
Create an APP to have a CHANCE for an interview? 

### ISSUE THREAD

**Issue by AzamatUmirzakov** [exercism/job-application-process#8]
And it is not even paid.
Seems like you guys just want to use candidates as a free workforce.
I don't even want to think what it is like to work for you.

**Comment by iHiD** [comment]
I'm closing this as it's not currently adding any value to the conversation. If you'd like to make tangible suggestions as to how hiring can be done well, please take a read of the [README](https://github.com/exercism/job-application-process/blob/main/README.md) and open a new issue. Thank you.
